# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gundam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Beast', 'beast'), ('Attack', 'attack'), ('Surveillance', 'surveillance')], max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Arturian', 'arturian')], max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('fractions', models.CharField(choices=[('Alliance', 'alliance'), ('Federations', 'federations'), ('Mars', 'mars')], max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='utils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utils_name', models.CharField(max_length=20)),
                ('utils_code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Aerial', 'aerial'), ('Ground', 'ground'), ('Mariner', 'mariner')], max_length=20)),
                ('descriptions', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=20)),
                ('weapon_code', models.CharField(max_length=20)),
                ('utils_type', models.CharField(choices=[('Sword', 'sword'), ('Canon', 'canon'), ('Bazooka', 'bazooka')], max_length=20)),
                ('descriptions', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='gundam',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.pilot'),
        ),
        migrations.AddField(
            model_name='gundam',
            name='utils',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.utils'),
        ),
        migrations.AddField(
            model_name='gundam',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.weapon'),
        ),
    ]
