# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gundam',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='utils',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
